travis:
  secure:
    BINSTAR_TOKEN: olxFzHGfZsGwVVUS8aMxjyFOLwH+TjCcxv5/88KyjF/PLDpwyLlnhCyHn8l6sXKe7yMs2yXxI/ntbcFA75Thc08G8EzUyY35qevyIFkzszLB87bN0rUUn/dHCOnNYA8myozxzNwOS7WdntfzUZVZBbtwGdKlT/vc98Fpud6t8OV+SEdZmF9BaYciXh+YrNdOPDy3VRqioWvONSLEVF5pkXQfRG+etO95cqq8JiZEQc4aJurVII0g3iOYCb/GvejNnBUE6QeoZKCRaFJBMBP6Q3gurf2WJCO16aLT3ip33S5bX5GQRWu3xw/RscQvm+PdB9iDpL11vR1TSEbgJUo3cDeIRDHxKOrM/ABVx/BEd8Z1EF/Zf70uWQAmO0785BxoqChYUnQi7Hw4psOsMLSF9sBrDmx6jAvZhkcARsEqo8tFaOQoVHfAcXznLnwg1ky1kxOWAs5BBxB7yvOJsb+l+EV5xcwC2KwogHiXAXUGm2thPsofffeQepy6V1mi9u+ceeoWsY2UKo35iUb1HmJ/Bz1JNbDNE7PzxRZiVgdUBhoefdEs3NeL1kF7UmR8Y3pbtWpYdNmtSFX69WwU8rsVSwVYtsWRd0DF8HoI5zVw8E0xsNuG2snbwwWMTpcQCaLiOUPeutbjtzHNckAXw3viI1Pp16RA59yOZH0/8Ay1GGU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
